# Generated by Django 4.2.17 on 2025-01-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('line', 'Line'), ('wechat', 'WeChat'), ('telegram', 'Telegram')], default='line', max_length=10)),
                ('contact_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
