# Generated by Django 4.2.17 on 2025-01-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmethod',
            name='contact_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
