# Generated by Django 4.2.17 on 2024-12-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('settled_price', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('actived', 'Actived'), ('completed', 'Completed')], default='actived', max_length=10)),
                ('direction', models.CharField(choices=[('buy_up', 'BuyUp'), ('buy_down', 'BuyDown')], default='buy_up', max_length=10)),
                ('settled_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
