# Generated by Django 4.2.17 on 2025-01-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='security_deposit',
            field=models.FloatField(default=0.0),
        ),
    ]
