# Generated by Django 4.2.17 on 2025-01-03 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_security_deposit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='security_deposit',
            new_name='buy_down_limit',
        ),
    ]
