name: CI/CD to AWS Elastic Beanstalk

env:
  RDS_DB_NAME: ${{ secrets.RDS_DB_NAME }}
  RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
  RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
  RDS_HOSTNAME: ${{ secrets.RDS_HOSTNAME }}
  RDS_PORT: ${{ secrets.RDS_PORT }}

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from GitHub
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run tests
    - name: Run tests
      run: |
        python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure the build job completes before deployment

    steps:
    # Checkout the code again in the deploy job
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up AWS CLI
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
      
    # Install the EB CLI using pip
    - name: Install EB CLI
      run: |
        python -m pip install --upgrade pip
        pip install awsebcli
    
    # Deploy to EB
    - name: Init EB CLI
      run: |
        eb init --platform python-3.9 --region ap-southeast-1 binary-product
    - name: Choose EB Env
      run: |
        eb use binary-product-env
    - name: Deploy to Elastic Beanstalk
      run: |
        eb deploy 